#!/bin/sh

export KAFKA_ADVERTISED_LISTENERS="${KAFKA_ADVERTISED_LISTENERS:-"PLAINTEXT://localhost:9092"}"
export KAFKA_CONTROLLER_LISTENER_NAMES="${KAFKA_CONTROLLER_LISTENER_NAMES:-"CONTROLLER"}"
export KAFKA_CONTROLLER_QUORUM_VOTERS="${KAFKA_CONTROLLER_QUORUM_VOTERS:-"1@localhost:9093"}"
export KAFKA_INTER_BROKER_LISTENER_NAME="${KAFKA_INTER_BROKER_LISTENER_NAME:-"PLAINTEXT"}"
export KAFKA_LISTENERS="${KAFKA_LISTENERS:-"PLAINTEXT://:9092,CONTROLLER://:9093"}"
export KAFKA_LOG_DIRS="${KAFKA_LOG_DIRS:-"/tmp/kafka"}"
export KAFKA_NODE_ID="${KAFKA_NODE_ID:-"1"}"
export KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR="${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-"1"}"
export KAFKA_PROCESS_ROLES="${KAFKA_PROCESS_ROLES:-"broker,controller"}"
export KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR="${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:-"1"}"
export KAFKA_TRANSACTION_STATE_LOG_MIN_ISR="${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR:-"1"}"
